version: '3'
services:
  auth:
    image: node:8-alpine
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    working_dir: /app
    command: 'sh -c "npm i && npm run dev"'
